#
# Traefik Forward Auth Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traefik-forward-auth
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "traefik-forward-auth"
        dapr.io/log-as-json: "true"
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: gcr.io/gci-ptfd-host-dev/oidc-forwardauth:v0.2.3 
        name: traefik-forward-auth
        ports:
        - containerPort: 4181
          protocol: TCP
        env:
        - name: PORT
          value: "4181"
        # - name: DOMAIN
        #   value: "docrender.net"
        - name: INSECURE_COOKIE
          value: "true"
        # Remove COOKIE_DOMAIN if not using auth host mode
        - name: COOKIE_DOMAIN
          value: "docrender.net"
        - name: AUTH_HOST
          value: "auth.docrender.net"
          # value: "auth.docrender.net:8443"
        - name: SCOPE
          value: "openid profile offline_access https://docrender.onmicrosoft.com/docrender/demo.read"
        - name: LOG_LEVEL
          value: trace
        - name: DEFAULT_PROVIDER
          value: oidc
        - name: PROVIDERS_OIDC_ISSUER_URL 
          value: https://docrender.b2clogin.com/tfp/f6a1f0af-38f9-4352-9325-f21c825dcd53/b2c_1_signin/v2.0/
        - name: PROVIDERS_OIDC_CLIENT_ID 
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: traefik-forward-auth-oidc-client-id
        - name: PROVIDERS_OIDC_CLIENT_SECRET 
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: traefik-forward-auth-oidc-client-secret
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: traefik-forward-auth-secret

---
#
# Auth Service
#
apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth
spec:
  type: ClusterIP
  selector:
    app: traefik-forward-auth
  ports:
  - name: auth-http
    port: 4181
    targetPort: 4181


---
#
# Secrets
#
# Kubernetes requires secret values to be converted to base64 when defined
# explicitly like this. (use `echo -n 'secret-value' | base64`)
#
# These are here for completeness, in reality you may define these elsewhere,
# for example using kustomize (shown in advanced examples)
#
apiVersion: v1
kind: Secret
metadata:
  name: traefik-forward-auth-secrets
  labels:
    app: traefik-forward-auth
type: Opaque
data:
  traefik-forward-auth-oidc-client-id: MmM1NjRlYTQtMWNkMi00NTljLWI3NWItZWVlYWE1MThjM2Fj
  traefik-forward-auth-oidc-client-secret: UlpZLXdTLmlJQ1RQdUtHNnA3VGZMOTE1ODJmQS05SjQuNQ==
  traefik-forward-auth-secret: MWwrMSFzNGswfkgsfDlKV2VARUU=